apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: springboot-hello-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: hello-project.com
      http:
        paths:
          - path: /hello
            pathType: Prefix
            backend:
              service:
                name: springboot-hello-service
                port:
                  number: 8080
