apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: springboot-hello-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: springboot.local
      http:
        paths:
          - path: /hello
            pathType: Prefix
            backend:
              service:
                name: springboot-hello-service
                port:
                  number: 8080
