apiVersion: v1
kind: Service
metadata:
  name: springboot-hello-service
spec:
  type: LoadBalancer
  selector:
    app: springboot-hello
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
